require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe UsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, password: '12345678', password_confirmation: '12345678' }
  }

  let(:invalid_attributes) {
    { first_name: Faker::Name.first_name, password: '1234567'}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #show" do
    it "returns a success response" do
      user = FactoryBot.create(:user)
      get :show, session: {user_id: user.id}
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      user = FactoryBot.create(:user)
      get :edit, session: { user_id: user.id }
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new User" do
        expect {
          post :create, params: {user: valid_attributes}, session: valid_session
        }.to change(User, :count).by(1)
      end

      it "redirects to the root url" do
        post :create, params: {user: valid_attributes}, session: valid_session
        expect(response).to redirect_to('/')
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {user: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, password: '87654321', password_confirmation: '87654321' }
      }
      let(:new_attributes_no_pass) {
        { first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, password: '', password_confirmation: ''}
      }

      it "updates the requested user" do
        user = FactoryBot.create(:user)
        expect {
          put :update, params: {user: new_attributes}, session: {user_id: user.id}
        }.to change {
          user.reload; user.authenticate('87654321')
        }.and change {
          user.first_name
        }.and change {
          user.last_name
        }.and change {
          user.email
        }
      end

      it "updates the requested user without changing password" do
        user = FactoryBot.create(:user, valid_attributes)
        expect {
          put :update, params: {user: new_attributes_no_pass}, session: { user_id: user.id }
        }.to change {
          user.reload; user.first_name
        }.and change {
          user.last_name
        }.and change {
          user.email
        }
        expect(user.authenticate('12345678')).to be_truthy
      end

      it "redirects to the user" do
        user = FactoryBot.create(:user)
        put :update, params: {user: valid_attributes}, session: { user_id: user.id }
        expect(response).to redirect_to(user)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        user = FactoryBot.create(:user)
        put :update, params: {user: invalid_attributes}, session: { user_id: user.id }
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested user" do
      user = FactoryBot.create(:user)
      expect {
        delete :destroy, session: { user_id: user.id}
      }.to change(User, :count).by(-1)
    end

    it "redirects to the root url" do
      user = FactoryBot.create(:user)
      delete :destroy, session: { user_id: user.id }
      expect(response).to redirect_to('/')
    end
  end

end
